// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Persistence;

#nullable disable

namespace School.Persistence.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School.Data.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd37818f-c8bb-4f15-8f5b-67e7f310a898"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 6, 12, 13, 43, 22, 775, DateTimeKind.Unspecified).AddTicks(9045), new TimeSpan(0, 0, 0, 0, 0)),
                            Credits = 3,
                            Duration = 3,
                            ModifiedBy = "Admin",
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 12, 13, 43, 22, 775, DateTimeKind.Unspecified).AddTicks(9050), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Minimal API Development"
                        },
                        new
                        {
                            Id = new Guid("63e64ad7-50b4-484c-895f-85b88e2f4115"),
                            CreatedBy = "Admin",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 6, 12, 13, 43, 22, 775, DateTimeKind.Unspecified).AddTicks(9052), new TimeSpan(0, 0, 0, 0, 0)),
                            Credits = 5,
                            Duration = 5,
                            ModifiedBy = "Admin",
                            ModifiedDate = new DateTimeOffset(new DateTime(2024, 6, 12, 13, 43, 22, 775, DateTimeKind.Unspecified).AddTicks(9053), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Ultimate API Development"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
